name: Run Linter
on: [push]
jobs:
  Run-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 20.8
      - uses: actions/checkout@v3
      - run: yarn install
      - run: yarn run build
      - run: yarn run linter-check
